version: '3.8'
name: mock-service
services:
  grpc-mock-service:
    build: server_mock/grpc-service
    container_name: grpc-mock-service
    volumes:
      - ./server_mock/grpc-service/wiremock-data/__files:/home/wiremock/__files
      - ./server_mock/grpc-service/wiremock-data/mappings:/home/wiremock/mappings
    ports:
      - "29090:8080"
  http-mock-service:
    image: wiremock/wiremock:3.6.0
    container_name: http-mock-service
    volumes:
      - ./server_mock/http-service/wiremock-data/__files:/home/wiremock/__files
      - ./server_mock/http-service/wiremock-data/mappings:/home/wiremock/mappings
    ports:
      - "28080:8080"